Melhorias de v3o2_automation     Ajustes de nomes     Cria default-tasks     Cria funcao get-param-func para reuso de codigo     Cria env.sh

diff --git a/v3o2_automation/jira/parent b/v3o2_automation/jira/parent
--- a/v3o2_automation/jira/parent
+++ b/v3o2_automation/jira/parent
@@ -1,18 +1,15 @@
 #!/bin/bash
 
-child=""
-function get_child() {
-    if test -n "$1"; then
-        child=$1
-    elif test ! -t 0; then
-        child=$( cat )
-    else
-        echo "Error: Provide child issue code."
-        exit 1
-    fi
-}
+source "$(dirname "$0")/../aux/get-param.sh"
 
-get_child $1
+get-param-func $1
+
+if [[ "$?" -eq 1 ]]; then
+    echo "Error: Provide child issue key."
+    exit 1
+fi
+
+child=$ret
 
 curl \
     -s \
diff --git a/v3o2_automation/jira/subtasks b/v3o2_automation/jira/subtasks
--- a/v3o2_automation/jira/subtasks
+++ b/v3o2_automation/jira/subtasks
@@ -1,20 +1,16 @@
 #!/bin/bash
 
-code=""
+source "$(dirname "$0")/../aux/get-param.sh"
 
-function get_code() {
-    if test -n "$1"; then
-        code=$1
-    elif test ! -t 0; then
-        code=$( cat )
-    else
-        echo "Error: Provide parent issue code."
-        exit 1
-    fi
-}
+get-param-func $1
 
-get_code $1
+if [[ "$?" -eq 1 ]]; then
+    echo "Error: Provide parent issue key."
+    exit 1
+fi
 
-jira issue list --parent $code --columns key,summary,status,assignee -s~"Closed"
+parent=$ret
+
+jira issue list --parent $parent --columns parent,summary,status,assignee -s~"Closed"
 
 exit $? 
diff --git a/v3o2_automation/jira/view-issue b/v3o2_automation/jira/view-issue
--- a/v3o2_automation/jira/view-issue
+++ b/v3o2_automation/jira/view-issue
@@ -1,19 +1,15 @@
 #!/bin/bash
 
-code=""
+source "$(dirname "$0")/../aux/get-param.sh"
 
-function get_code() {
-    if test -n "$1"; then
-        code=$1
-    elif test ! -t 0; then
-        code=$( cat )
-    else
-        echo "Error: Provide issue code."
-        exit 1
-    fi
-}
+get-param-func $1
 
-get_code $1
+if [[ "$?" -eq 1 ]]; then
+    echo "Error: Provide issue key."
+    exit 1
+fi
 
-jira issue view $code
+key=$ret
+
+jira issue view $key
 exit $?
diff --git a/v3o2_automation/workflow/create-mr b/v3o2_automation/workflow/create-mr
--- a/v3o2_automation/workflow/create-mr
+++ b/v3o2_automation/workflow/create-mr
@@ -1,11 +1,22 @@
 #!/bin/bash
 
+source "$(dirname "$0")/../aux/get-param.sh"
+
 # git 1.8.4
 if [ -d "/opt/rh/devtoolset-2/" ]; then
     export PATH="/opt/rh/devtoolset-2/root/usr/bin/":$PATH
 fi
 
-label=`doing | team`
+get-param-func $1
+
+if [[ "$?" -eq 1 ]]; then
+    echo "Error: Provide target branch."
+    exit 1
+fi
+
+target_branch=$ret
+
+label=`jira me | doing | team`
 
 glab mr create \
     --fill \
@@ -13,10 +24,9 @@ glab mr create \
     --assignee `jira me` \
     --allow-collaboration \
     --remove-source-branch \
-    --target-branch master \
+    --target-branch $target_branch \
     --label "$label" \
     --push \
-    --yes && \
-    mv-issue `doing` "Ready To Code Review"
+    --yes
 
 exit $?
